// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: repeater/v1/main.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Repeater_Stream_FullMethodName    = "/repeater.v1.Repeater/Stream"
	Repeater_LogStream_FullMethodName = "/repeater.v1.Repeater/LogStream"
	Repeater_Debug_FullMethodName     = "/repeater.v1.Repeater/Debug"
)

// RepeaterClient is the client API for Repeater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepeaterClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Repeater_StreamClient, error)
	LogStream(ctx context.Context, opts ...grpc.CallOption) (Repeater_LogStreamClient, error)
	Debug(ctx context.Context, opts ...grpc.CallOption) (Repeater_DebugClient, error)
}

type repeaterClient struct {
	cc grpc.ClientConnInterface
}

func NewRepeaterClient(cc grpc.ClientConnInterface) RepeaterClient {
	return &repeaterClient{cc}
}

func (c *repeaterClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Repeater_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Repeater_ServiceDesc.Streams[0], Repeater_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &repeaterStreamClient{stream}
	return x, nil
}

type Repeater_StreamClient interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ClientStream
}

type repeaterStreamClient struct {
	grpc.ClientStream
}

func (x *repeaterStreamClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *repeaterStreamClient) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repeaterClient) LogStream(ctx context.Context, opts ...grpc.CallOption) (Repeater_LogStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Repeater_ServiceDesc.Streams[1], Repeater_LogStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &repeaterLogStreamClient{stream}
	return x, nil
}

type Repeater_LogStreamClient interface {
	Send(*Log) error
	Recv() (*Log, error)
	grpc.ClientStream
}

type repeaterLogStreamClient struct {
	grpc.ClientStream
}

func (x *repeaterLogStreamClient) Send(m *Log) error {
	return x.ClientStream.SendMsg(m)
}

func (x *repeaterLogStreamClient) Recv() (*Log, error) {
	m := new(Log)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repeaterClient) Debug(ctx context.Context, opts ...grpc.CallOption) (Repeater_DebugClient, error) {
	stream, err := c.cc.NewStream(ctx, &Repeater_ServiceDesc.Streams[2], Repeater_Debug_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &repeaterDebugClient{stream}
	return x, nil
}

type Repeater_DebugClient interface {
	Send(*DebugResponse) error
	Recv() (*Request, error)
	grpc.ClientStream
}

type repeaterDebugClient struct {
	grpc.ClientStream
}

func (x *repeaterDebugClient) Send(m *DebugResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *repeaterDebugClient) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RepeaterServer is the server API for Repeater service.
// All implementations must embed UnimplementedRepeaterServer
// for forward compatibility
type RepeaterServer interface {
	Stream(Repeater_StreamServer) error
	LogStream(Repeater_LogStreamServer) error
	Debug(Repeater_DebugServer) error
	mustEmbedUnimplementedRepeaterServer()
}

// UnimplementedRepeaterServer must be embedded to have forward compatible implementations.
type UnimplementedRepeaterServer struct {
}

func (UnimplementedRepeaterServer) Stream(Repeater_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedRepeaterServer) LogStream(Repeater_LogStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LogStream not implemented")
}
func (UnimplementedRepeaterServer) Debug(Repeater_DebugServer) error {
	return status.Errorf(codes.Unimplemented, "method Debug not implemented")
}
func (UnimplementedRepeaterServer) mustEmbedUnimplementedRepeaterServer() {}

// UnsafeRepeaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepeaterServer will
// result in compilation errors.
type UnsafeRepeaterServer interface {
	mustEmbedUnimplementedRepeaterServer()
}

func RegisterRepeaterServer(s grpc.ServiceRegistrar, srv RepeaterServer) {
	s.RegisterService(&Repeater_ServiceDesc, srv)
}

func _Repeater_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepeaterServer).Stream(&repeaterStreamServer{stream})
}

type Repeater_StreamServer interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type repeaterStreamServer struct {
	grpc.ServerStream
}

func (x *repeaterStreamServer) Send(m *Request) error {
	return x.ServerStream.SendMsg(m)
}

func (x *repeaterStreamServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Repeater_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepeaterServer).LogStream(&repeaterLogStreamServer{stream})
}

type Repeater_LogStreamServer interface {
	Send(*Log) error
	Recv() (*Log, error)
	grpc.ServerStream
}

type repeaterLogStreamServer struct {
	grpc.ServerStream
}

func (x *repeaterLogStreamServer) Send(m *Log) error {
	return x.ServerStream.SendMsg(m)
}

func (x *repeaterLogStreamServer) Recv() (*Log, error) {
	m := new(Log)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Repeater_Debug_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepeaterServer).Debug(&repeaterDebugServer{stream})
}

type Repeater_DebugServer interface {
	Send(*Request) error
	Recv() (*DebugResponse, error)
	grpc.ServerStream
}

type repeaterDebugServer struct {
	grpc.ServerStream
}

func (x *repeaterDebugServer) Send(m *Request) error {
	return x.ServerStream.SendMsg(m)
}

func (x *repeaterDebugServer) Recv() (*DebugResponse, error) {
	m := new(DebugResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Repeater_ServiceDesc is the grpc.ServiceDesc for Repeater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Repeater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repeater.v1.Repeater",
	HandlerType: (*RepeaterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Repeater_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "LogStream",
			Handler:       _Repeater_LogStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Debug",
			Handler:       _Repeater_Debug_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "repeater/v1/main.proto",
}
