---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fullname" . }}-{{ .Release.Namespace }}
rules:
  # Allow listing and getting namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Allow listing and getting services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  # Allow listing and getting ingresses
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  # Allow listing and getting Istio resources (optional)
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices", "gateways", "destinationrules"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "fullname" . }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
